# Generated by Django 4.0.4 on 2022-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usertokens_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
