# Generated by Django 4.0.4 on 2022-05-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usertokens_expired_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
